def print_menu():
    print("==== Blockchain Simulator ====")
    print("1. Add new block")
    print("2. View blockchain")
    print("3. Validate blockchain")
    print("4. Tamper with a block")
    print("5. Forensic audit")
    print("6. Repair chain (re-mine)")
    print("7. Rollback to checkpoint")
    print("8. Exit")